apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

resources:
  - ../../base

# Patch deployment with environment-specific values
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: mlflow-kserve-webhook-listener

# You can override the image here
images:
  - name: ghcr.io/nebari-dev/mlflow-kserve-webhook-listener
    newTag: latest

# Secret reference (users need to create this separately)
# kubectl create secret generic mlflow-webhook-secret \
#   --from-literal=secret=your-webhook-secret-here \
#   -n mlflow
