[project]
name = "nebari-mlflow-webhook-listener"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
dev = "uvicorn src.main:app --reload"
test = "pytest"

[dependencies]
python = ">=3.10,<3.14"
pip = "*"

[pypi-dependencies]
fastapi = ">=0.115.0"
uvicorn = { version = ">=0.30.0", extras = ["standard"] }
pydantic = ">=2.0.0"
pydantic-settings = ">=2.0.0"
kubernetes = ">=29.0.0"
mlflow = ">=3.2.0"
jinja2 = ">=3.1.0"
pyyaml = ">=6.0"
httpx = ">=0.27.0"
nebari-mlflow-webhook-listener = { path = ".", editable = true }

[feature.dev.pypi-dependencies]
pytest = ">=8.0.0"
pytest-asyncio = ">=0.23.0"
pytest-mock = ">=3.12.0"
jupyterlab = "*"
scikit-learn = "*"
pandas = "*"
numpy = "*"
ruff = ">=0.14.0, <0.15"

[environments]
default = { features = [], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
