apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-webhook-listener-tls
  namespace: kserve-mlflow
spec:
  # The secret name where the certificate will be stored
  secretName: mlflow-webhook-listener-tls

  # Certificate duration and renewal
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration

  # Internal DNS names for the service
  dnsNames:
    - mlflow-kserve-webhook-listener.kserve-mlflow.svc
    - mlflow-kserve-webhook-listener.kserve-mlflow.svc.cluster.local
    - mlflow-kserve-webhook-listener

  # Issuer reference - using a self-signed issuer for internal certs
  # You may need to create this ClusterIssuer first (see below)
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
