image:
  registry: docker.io
  repository: bitnamilegacy/mlflow
  tag: 3.3.2-debian-12-r0

run:
  enabled: false

tracking:
  auth:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 5000

postgresql:
  # TODO: Remove hardcoded image values after Helm chart update
  # This is a workaround due to bitnami charts deprecation
  # See: https://github.com/bitnami/charts/issues/35164
  # See: https://github.com/nebari-dev/nebari/issues/3120
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4

waitContainer:
  # TODO: Remove hardcoded image values after Helm chart update
  # This is a workaround due to bitnami charts deprecation
  # See: https://github.com/bitnami/charts/issues/35164
  # See: https://github.com/nebari-dev/nebari/issues/3120
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r51

volumePermissions:
  # TODO: Remove hardcoded image values after Helm chart update
  # This is a workaround due to bitnami charts deprecation
  # See: https://github.com/bitnami/charts/issues/35164
  # See: https://github.com/nebari-dev/nebari/issues/3120
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r51
