---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-kserve-webhook-listener
  labels:
    app: mlflow-kserve-webhook-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-kserve-webhook-listener
  template:
    metadata:
      labels:
        app: mlflow-kserve-webhook-listener
    spec:
      serviceAccountName: mlflow-kserve-webhook-listener
      containers:
      - name: listener
        image: ghcr.io/nebari-dev/mlflow-kserve-webhook-listener:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        # Environment variables are defined in overlays
        env: []

        volumeMounts:
        - name: template
          mountPath: /etc/templates
          readOnly: true

        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

      volumes:
      - name: template
        configMap:
          name: inference-service-template

      securityContext:
        fsGroup: 1000
