apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: mlflow-kserve-webhook-listener
      managed-by: kustomize

# Note: The ConfigMap with the InferenceService template is defined
# in configmap.yaml. Users can customize it in their overlays if needed.
