apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

resources:
  - ../../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: mlflow-kserve-webhook-listener

images:
  - name: ghcr.io/nebari-dev/mlflow-kserve-webhook-listener
    newTag: latest
